# Generated by Django 5.2.4 on 2025-08-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolecture',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
