# Generated by Django 5.2.4 on 2025-08-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiolecture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolecture',
            name='flashcards',
            field=models.TextField(blank=True, null=True),
        ),
    ]
